name: Matrix demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include: # reserved key. aca, por ejemplo, solo va a intentar UNA de estas combinaciones. 18 y ubuntu, no la suma a las otras.
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: # aca se saca de la matrix la combinacion version 12 con windows.
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }} # esto corre una vez por cada value del campo operating, y corren en paralelo
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      